# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, null=True)),
                ('password', models.CharField(max_length=64, null=True)),
                ('email', models.CharField(max_length=32, null=True)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
