# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('detail', models.CharField(max_length=64, null=True)),
                ('Img', models.CharField(max_length=64, null=True)),
                ('time', models.CharField(max_length=16, null=True)),
                ('iscollected', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
