# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0002_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='Img',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
