# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0003_auto_20180420_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='collected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_list', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='rock.movies')),
                ('user_list', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to='rock.userinfo')),
            ],
            options={
                'db_table': 'collexted',
            },
        ),
    ]
