# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0004_collected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='iscollected',
        ),
    ]
